# Model configuration
model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct
dtype: bfloat16

# Script arguments
dataset_source: apps 
dataset_train_split: test
dataset_test_split: test
dataset_train_max_samples: 1000

# Training configuration (GRPOConfig)
output_dir: ./checkpoints
learning_rate: 1.0e-5
per_device_train_batch_size: 1 
gradient_accumulation_steps: 32
num_generations: 4
num_train_epochs: 3
max_prompt_length: 512
max_completion_length: 512
logging_steps: 1
save_strategy: epoch
report_to: wandb
# Evaluation configuration
eval_strategy: steps
eval_steps: 10
per_device_eval_batch_size: 4
run_name: grpo7b-1201-classeval
temperature: 0.7
beta: 0.0
gradient_checkpointing: true

# LoRA configuration
use_peft: true
lora_r: 4
lora_alpha: 16
lora_target_modules: all-linear
# lora_target_modules:
#   - q_proj
#   - v_proj

# Reward configuration
tests_weight: 0.5
ruff_weight: 0.25
mypy_weight: 0.25
syntax_error_penalty: -1.0
ruff_select:
- F
- E
- W
- C90
- N
- UP
- B
- A
- C4
- RET
- SIM
- ARG

ruff_ignore:
- E501
- E741
- W292

# Custom configurations
seed: 42